on:
  schedule:
    - cron: "*/5 * * * *"

name: Web-Scraping-ZAP-Imoveis

jobs:
  lint-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - name: Instalando o remotes e o pacote purrr do GitHub
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('tidyverse/purrr')"
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::remotes
            any::purrr
            any::dplyr
            any::xml2
            any::zeallot
            any::abjutils
            any::stringr
            any::httr
            any::gt
            any::jsonlite
            any::tidygeocoder
            any::rvest
        
      - name: Web Scraping
        run: |
          source("scraping_github_action.R")
        shell: Rscript {0}
            
      - name: Commits
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'Dados obtidos por web scraping atualizado' || echo "Dados obtidos por web scraping atualizado"
          git push origin || echo "Base de dados atualizada"