# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
  - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches: main

name: Web-Scraping-ZAP-Imoveis

jobs:
  lint-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
        
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::remotes
            any::purrr
            any::dplyr
            any::xml2
            any::zeallot
            any::abjutils
            any::stringr
            any::httr
            any::gt
            any::jsonlite
            any::tidygeocoder
        
      - name: Web Scraping
        run: |
          Rscript scraping_github_action.R
            
      - name: Commits
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"