# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
  - cron: "15 12 * * *"
  workflow_dispatch:

name: Web-Scraping-ZAP-Imoveis

jobs:
  lint-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
        
      - name: Dependencias do GitHub
        run: |
          install.packages(c("dplyr","stringr","glue","xml2","httr","zeallot","abjutils","gt","jsonlite", "remotes", "tidygeocoder"))
          library(remotes)
          install_github("tidyverse/purrr")
          
      - name: Web Scraping
        run: |
          Rscript scraping_github_action.R
            
      - name: Commits
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"