on:
  schedule:
    - cron: '*/5 * * * *'

name: Web-Scraping-ZAP-Imoveis

jobs:
  lint-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::remotes
            any::dplyr
            any::xml2
            any::zeallot
            any::abjutils
            any::stringr
            any::httr
            any::gt
            any::jsonlite
            any::tidygeocoder
            any::rvest
          
      - name: Raspando e Salvando
        run: |
          remotes::install_github("tidyverse/purrr", force = TRUE)
          source("R/teste.R")
        shell: Rscript {0}
            
      - name: Commits
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Web Scraping realizado (atualizacao concluida)"
          git push origin main