# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
  - cron: "15 12 * * *"
  workflow_dispatch:

name: Web-Scraping-ZAP-Imoveis

jobs:
  lint-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
        
      - name: Dependencias do GitHub
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("tidyverse/purrr")
          remotes::install_cran("dplyr")
          remotes::install_cran("xml2")
          remotes::install_cran("zeallot")
          remotes::install_cran("abjutils")
          remotes::install_cran("stringr")
          remotes::install_cran("httr")
          remotes::install_cran("gt")
          remotes::install_cran("jsonlite")
          remotes::install_cran("tidygeocoder")
        shell: Rscript {0}
        
      - name: Web Scraping
        run: |
          Rscript scraping_github_action.R
            
      - name: Commits
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"